vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        quizz_images:
            uri_prefix: /images/movies
            upload_destination: '%kernel.project_dir%/public/images/movies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profile_images:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
